### PR TITLE
Fix MaintenancePlaceholder unregistering when reloading PAPI

### LINKED ISSUE #1: [BUG] Not working after Papi reload
%maintenance_status% and %maintenance_server_<name>%
Stops working after /papi reload

### PR DESCRIPTION
**Pull request by fabianmakila**
fixes #1

### CODE REVIEW

**Comment by kennytv** [comment]
Can you also bump the version to 2.0.5, ~~so I dont have to~~? see https://github.com/kennytv/MaintenanceAddon/commit/48b52b449509c167f743e419b91ef2fe6a5379f3

**Comment by fabianmakila** [comment]
> Can you also bump the version to 2.0.5, ~so I dont have to~? see [48b52b4](https://github.com/kennytv/MaintenanceAddon/commit/48b52b449509c167f743e419b91ef2fe6a5379f3)

Done!

**Review by kennytv — APPROVED** [review]
Thanks!

**Comment by CodeByCam** [comment]
Thanks Fabian! ^_^

**Comment by TheBjoRedCraft** [comment]
Thanks Fabian! ^_^

**Comment by TheBjoRedCraftDev** [comment]
Thanks Fabian! ^_^

**Comment by CodeByCam** [comment]
@TheBjoRedCraft & @TheBjoRedCraftDev Whilst I do appreciate your enthusiasm in thanking people, please don't try to flood the PR with comments! Thanks! ^_^

**Pull request merged**
